export const COMPANY_FIND_REQUEST = "COMPANY_FIND_REQUEST"
export const COMPANY_FIND_SUCCESS = "COMPANY_FIND_SUCCESS"
export const COMPANY_FIND_FAIL = "COMPANY_FIND_FAIL"

export const COMPANY_FINDONE_REQUEST = "COMPANY_FINDONE_REQUEST"
export const COMPANY_FINDONE_SUCCESS = "COMPANY_FINDONE_SUCCESS"
export const COMPANY_FINDONE_FAIL = "COMPANY_FINDONE_FAIL"

export const COMPANY_FINDONE1_REQUEST = "COMPANY_FINDONE1_REQUEST"
export const COMPANY_FINDONE1_SUCCESS = "COMPANY_FINDONE1_SUCCESS"
export const COMPANY_FINDONE1_FAIL = "COMPANY_FINDONE1_FAIL"
